Refactor RELEASE script a bit

diff --git a/RELEASE b/RELEASE
--- a/RELEASE
+++ b/RELEASE
@@ -12,24 +12,22 @@ if [ -n "$(git status --porcelain)" ]; then
     exit 1
 fi
 
-echo 'Version number is:'
-echo
-cat VERSION || ( echo "VERSION file doesn't exist; aborting release" ; exit 1 )
-echo
+if [ -f VERSION ]; then
+    echo 'Version number is:'
+    echo
+    cat VERSION
+    echo
+else
+    echo "VERSION file doesn't exist; aborting release"
+    exit 1
+fi
 
-release=./beluga-$(cat VERSION)
+release="./beluga-$(cat VERSION)"
 
 echo 'Release directory name is:'
 echo
 echo "    ${release}"
 echo
-
-echo 'Building (bytecode) in-tree first, for testing ...'
-make clean
-make BYTE=1 || ( echo 'make failed; aborting release.' ; exit 1 )
-
-echo 'Running TEST (bytecode) ...'
-./TEST --examples || ( echo 'TEST failed; aborting release.' ; exit 1 )
 
 echo 'Building (native) in-tree first, for testing ...'
 make clean
@@ -79,36 +77,35 @@ cp -a \
 
 (
     cd "${release}"
-    echo Deleting useless files:
+    echo "Deleting useless files:"
     useless=$(find . -print | grep -E '~|.DS_Store' || true)
-    echo rm -rf "${useless}"
+    echo "rm -rf ${useless}"
     rm -rf "${useless}"
 
     # Remove examples not yet ready for public consumption
-    echo rm -rf examples/{notworking,cfg,beluga}
+    echo "rm -rf examples/{notworking,cfg,beluga}"
     rm -rf examples/{notworking,cfg,beluga}
 
     echo "Copying ${release} to ${release-sandbox} ..."
 )
 
-if [ -e "${release}-sandbox" ]; then
-    echo Release sandbox directory "$release-sandbox" already exists.
+release_sandbox="${release}-sandbox"
+
+if [ -e "${release_sandbox}" ]; then
+    echo "Release sandbox directory $release-sandbox already exists."
     exit 1
 fi
-cp -a "${release}" "${release}-sandbox"
+cp -a "${release}" "${release_sandbox}"
 
 (
-    cd "${release}-sandbox"
-
-    echo 'Building (bytecode) in release directory ...'
-    make BYTE=1 || ( echo 'make failed; aborting release.' ; exit 1 )
+    cd "${release_sandbox}"
 
     echo 'Building (native) in release directory ...'
     make clean
     make || ( echo 'native make failed; aborting release.' ; exit 1 )
 )
 
-echo "Leaving ${release}-sandbox around if you want to test further."
+echo "Leaving ${release_sandbox} around if you want to test further."
 
 echo "Building archive ${release}.tar.gz"
 tar zcf "${release}.tar.gz" "${release}" || ( echo 'tar failed.' ; exit 1 )
