Fix testing workflow on MacOS
The MacOS file system is not case sensitive, so the directory `./test` is conflicting with the test script `./TEST`.
This is addressed by renaming `./TEST` to `./TEST.sh`.

diff --git a/RELEASE b/RELEASE
--- a/RELEASE
+++ b/RELEASE
@@ -34,7 +34,7 @@ make clean
 make || ( echo 'native make failed; aborting release.' ; exit 1 )
 
 echo 'Running TEST (native) ...'
-./TEST --examples || ( echo 'TEST failed; aborting release.' ; exit 1 )
+./TEST.sh --examples || ( echo 'TEST failed; aborting release.' ; exit 1 )
 
 if [ -e "${release}" ]; then
     echo "Release directory ${release} already exists."
