Turn RELEASE flag on when building in ./RELEASE script.

diff --git a/RELEASE b/RELEASE
--- a/RELEASE
+++ b/RELEASE
@@ -99,12 +99,12 @@ echo 'Running TEST (native)'
 cd $release-sandbox
 
 echo 'Building (bytecode) in release directory'
-omake || ( echo 'omake failed; aborting release' ; exit 1 )
+omake RELEASE=true || ( echo 'omake failed; aborting release' ; exit 1 )
 
 echo 'Building (native) in release directory'
-omake clean
-omake NATIVE_ENABLED=true clean
-omake NATIVE_ENABLED=true || ( echo 'native omake failed; aborting release' ; exit 1 )
+omake RELEASE=true clean
+omake RELEASE=true NATIVE_ENABLED=true clean
+omake RELEASE=true NATIVE_ENABLED=true || ( echo 'native omake failed; aborting release' ; exit 1 )
 
 cd ..
 echo 'Leaving '$release-sandbox' around if you want to test further'
