Refactor shell programs with shellcheck

diff --git a/RELEASE b/RELEASE
--- a/RELEASE
+++ b/RELEASE
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-set -e
+set -u
 
 # tests that the output of git status --porcelain is non-empty
 if [ -n "$(git status --porcelain)" ]; then
@@ -17,11 +17,11 @@ echo
 cat VERSION || ( echo "VERSION file doesn't exist; aborting release" ; exit 1 )
 echo
 
-release=./beluga-`cat VERSION`
+release=./beluga-$(cat VERSION)
 
 echo 'Release directory name is:'
 echo
-echo '    '$release
+echo "    ${release}"
 echo
 
 echo 'Building (bytecode) in-tree first, for testing ...'
@@ -38,12 +38,12 @@ make || ( echo 'native make failed; aborting release.' ; exit 1 )
 echo 'Running TEST (native) ...'
 ./TEST --examples || ( echo 'TEST failed; aborting release.' ; exit 1 )
 
-if [ -e $release ]; then
-    echo Release directory "$release" already exists.
+if [ -e "${release}" ]; then
+    echo "Release directory ${release} already exists."
     exit 1
 fi
 
-mkdir $release
+mkdir "${release}"
 
 echo 'Copying files in root ...'
 cp -a \
@@ -55,9 +55,9 @@ cp -a \
     myocamlbuild.ml \
     Makefile \
     _tags \
-    $release
+    "${release}"
 
-mkdir $release/bin
+mkdir "${release}/bin"
 
 # Set the RELEASE to true by default.
 # sed -i 's/RELEASE *= *false/RELEASE = true/' $release
@@ -65,51 +65,54 @@ mkdir $release/bin
 echo 'Copying src ...'
 cp -a \
     src \
-    $release
+    "${release}"
 
 echo 'Copying tools ...'
 cp -a \
     tools \
-    $release
+    "${release}"
 
 echo 'Copying examples ...'
 cp -a \
     examples \
-    $release
+    "${release}"
 
-cd $release
-echo Deleting useless files:
-useless=$(find . -print | egrep '~|.DS_Store' || true)
-echo rm -rf $useless
-rm -rf $useless
+(
+    cd "${release}"
+    echo Deleting useless files:
+    useless=$(find . -print | grep -E '~|.DS_Store' || true)
+    echo rm -rf "${useless}"
+    rm -rf "${useless}"
 
-# Remove examples not yet ready for public consumption
-echo rm -rf examples/{notworking,cfg,beluga}
-rm -rf examples/{notworking,cfg,beluga}
+    # Remove examples not yet ready for public consumption
+    echo rm -rf examples/{notworking,cfg,beluga}
+    rm -rf examples/{notworking,cfg,beluga}
 
-echo "Copying $release to $release-sandbox ..."
-cd ..
-if [ -e $release-sandbox ]; then
+    echo "Copying ${release} to ${release-sandbox} ..."
+)
+
+if [ -e "${release}-sandbox" ]; then
     echo Release sandbox directory "$release-sandbox" already exists.
     exit 1
 fi
-cp -a $release $release-sandbox
+cp -a "${release}" "${release}-sandbox"
 
-cd $release-sandbox
+(
+    cd "${release}-sandbox"
 
-echo 'Building (bytecode) in release directory ...'
-make BYTE=1 || ( echo 'make failed; aborting release.' ; exit 1 )
+    echo 'Building (bytecode) in release directory ...'
+    make BYTE=1 || ( echo 'make failed; aborting release.' ; exit 1 )
 
-echo 'Building (native) in release directory ...'
-make clean
-make || ( echo 'native make failed; aborting release.' ; exit 1 )
+    echo 'Building (native) in release directory ...'
+    make clean
+    make || ( echo 'native make failed; aborting release.' ; exit 1 )
+)
 
-cd ..
-echo 'Leaving '$release-sandbox' around if you want to test further.'
+echo "Leaving ${release}-sandbox around if you want to test further."
 
-echo 'Building archive' $release.tar.gz
-tar zcf $release.tar.gz $release || ( echo 'tar failed.' ; exit 1 )
+echo "Building archive ${release}.tar.gz"
+tar zcf "${release}.tar.gz" "${release}" || ( echo 'tar failed.' ; exit 1 )
 echo
-ls -l $release.tar.gz
+ls -l "${release}.tar.gz"
 echo
 echo "Release built.  Don't forget to "'`'"git push' if needed."
diff --git a/TEST b/TEST
--- a/TEST
+++ b/TEST
@@ -1,5 +1,7 @@
 #!/usr/bin/env zsh
 
+set -u
+
 usage() {
     echo "Usage: $0 [test-options] -- [beluga-options]"
     echo
@@ -8,8 +10,8 @@ usage() {
     echo "Options:"
     echo "  -h,--help        Display this usage information."
     echo "  -c,--color       Force colorized output even when piped."
-    echo "  --noexamples     Do not also test $EXAMPLEDIR."
-    echo "  --examples       Only test $EXAMPLEDIR."
+    echo "  --noexamples     Do not also test ${EXAMPLEDIR}."
+    echo "  --examples       Only test ${EXAMPLEDIR}."
     echo "  --interactive    Only test the interactive mode."
     echo "  --reset          Replace all .out files with new output (use with caution!)."
     echo "  --stop           Stop on the first failed test."
@@ -22,13 +24,14 @@ usage() {
 }
 
 STOP=0
+RESET=
 
 # Allow file globs to match nothing.
 setopt null_glob
 
 # Find test cases.
 test_cases() {
-    for dir in $TESTDIR/**/ $EXAMPLEDIR/**/ ; do
+    for dir in ${TESTDIR}/**/ ${EXAMPLEDIR}/**/ ; do
         cfgs=(${dir}*.cfg)
         if (( ${#cfgs[@]} > 0 )) ; then
             print -C1 ${dir}*.cfg
@@ -41,7 +44,7 @@ test_cases() {
 sort_cases() {
     cases=($(</dev/stdin))
     for i in ${(M)cases#*.bel}; do
-        wc -c $i;
+        wc -c "${i}";
     done | sort -n | awk '{print $2}'
     print -C1 ${(M)cases#*.cfg}
 }
@@ -50,86 +53,93 @@ do_testing() {
     local n=0 success=0 fail=0 timeout=0 admissible=0 lexer_fail=0 replay_fail=0
 
     # Limit runtime of each test case, in seconds.
-    ulimit -t $TIMEOUT
+    ulimit -t "${TIMEOUT}"
 
     for i in $(test_cases | sort -n) ; do
         n=$((n+1))
-        echo -ne "$C[start]**$CEND TEST $n: $i ... "
-        local uhoh=0
+        echo -ne "${C[start]}**${CEND} TEST ${n}: ${i} ... "
 
-        result=$($LEX_CHECK "$i" 2>&1)
+        result=$(${LEX_CHECK} "${i}" 2>&1)
         exit_code=$?
 
-        if [ $exit_code -eq 2 ] ; then
+        if [ ${exit_code} -eq 2 ] ; then
             let lexer_fail=lexer_fail+1
-            echo -e "$C[lex_fail]FATAL LEXER FAILURE$CEND"
-            test $STOP -eq 1 && exit 1 || continue
+            echo -e "${C[lex_fail]}FATAL LEXER FAILURE${CEND}"
+            test ${STOP} -eq 1 && exit 1 || continue
         fi
 
-        if [ $exit_code -ne 0 ] ; then
+        if [ ${exit_code} -ne 0 ] ; then
             lexer_fail=$((lexer_fail+1))
-            echo -en "$C[lex_fail]LEXER FAILURE$CEND "
-            test $STOP -eq 1 && exit 1
+            echo -en "${C[lex_fail]}LEXER FAILURE${CEND}"
+            test ${STOP} -eq 1 && exit 1
         fi
 
-        result=$($EXE +test $* $i 2>&1)
+        result=$(${EXE} +test $* "${i}" 2>&1)
         exit_code=$?
-        diff_result=$(printf "%s" $result | diff -b -u $i.out - 2>/dev/null)
+        diff_result=$(printf "%s" "${result}" | diff -b -u "${i}.out" - 2>/dev/null)
         # diff responds 0 if same, 1 if different, 2 if couldn't compare.
         diff_code=$?
 
-        if [[ $exit_code -eq 152 ]]
+        echo "${diff_code}"
+
+        if [[ ${exit_code} -eq 152 ]]
         then
-            echo -e "$C[timeout]TIMEOUT$CEND"
+            echo -e "${C[timeout]}TIMEOUT${CEND}"
             timeout=$((timeout+1))
-            test $STOP -eq 1 && exit 1
-        elif [[ $diff_code -eq 0 || (exit_code -eq 0 && $diff_code -eq 2) ]]
+            test ${STOP} -eq 1 && exit 1
+        elif [[ "${diff_code}" -eq 0 || (exit_code -eq 0 && "${diff_code}" -eq 2) ]]
         then
-            echo -e "$C[ok]OK$CEND"
+            echo -e "${C[ok]}OK${CEND}"
             success=$((success+1))
         else
-            if grep --quiet "$i" .admissible-fail ; then
-                echo -e "$C[admissible]ADMISSIBLE$CEND"
+            if grep --quiet "${i}" .admissible-fail ; then
+                echo -e "${C[admissible]}ADMISSIBLE${CEND}"
                 admissible=$((admissible+1))
             else
-                echo -e "$C[fail]FAIL$CEND"
+                echo -e "${C[fail]}FAIL${CEND}"
                 fail=$((fail+1))
-                [[ -z "$diff_result" ]] && echo "$result" || (echo "$diff_result" | colorize_diff)
-                test $STOP -eq 1 && exit 1
+
+                if [[ -z "${diff_result}" ]]; then
+                    echo "${result}"
+                else
+                    echo "${diff_result}" | colorize_diff
+                fi
+
+                test ${STOP} -eq 1 && exit 1
             fi
         fi
 
-        [[ -n $RESET && -f $i.out ]] && echo "$result" > $i.out
+        [[ -n "${RESET}" && -f "${i}.out" ]] && echo "${result}" > "${i}.out"
     done
 
     echo "===== INTERACTIVE MODE TESTS ====="
 
-    for i in $(find $INTERACTIVE_TESTDIR -type f | sort -n) ; do
+    for i in $(find "${INTERACTIVE_TESTDIR}" -type f | sort -n) ; do
         n=$((n+1))
-        echo -ne "$C[start]**$CEND TEST $n: $i ... "
+        echo -ne "${C[start]}**${CEND} TEST ${n}: ${i} ... "
 
-        result=$($REPLAY "$i" 2>&1)
+        result=$(${REPLAY} "${i}" 2>&1)
         exit_code=$?
 
-        if [ $exit_code -eq 152 ] ; then
-            echo -e "$C[timeout]TIMEOUT$CEND"
+        if [ ${exit_code} -eq 152 ] ; then
+            echo -e "${C[timeout]}TIMEOUT${CEND}"
             timeout=$((timeout + 1))
-        elif [ $exit_code -ne 0 ] ; then
-            echo -e "$C[fail]FAIL$CEND"
+        elif [ ${exit_code} -ne 0 ] ; then
+            echo -e "${C[fail]}FAIL${CEND}"
             replay_fail=$((replay_fail + 1))
         else
-            echo -e "$C[ok]OK$CEND"
+            echo -e "${C[ok]}OK${CEND}"
         fi
     done
 
     echo
-    echo Successes: $success
-    echo Failures: $fail
-    echo Lexer failures: $lexer_fail
-    echo Admissible failures: $admissible
-    echo Timeouts: $timeout
-    echo Interactive mode failures: $replay_fail
-    echo Total: $n
+    echo Successes: ${success}
+    echo Failures: ${fail}
+    echo Lexer failures: ${lexer_fail}
+    echo Admissible failures: ${admissible}
+    echo Timeouts: ${timeout}
+    echo Interactive mode failures: ${replay_fail}
+    echo Total: ${n}
 
     echo
     times
@@ -138,7 +148,7 @@ do_testing() {
     # If not all tests succeeded then exit with non-zero status.
     # double-negate the failure count to get 0 if it was zero, and
     # 1 if it was nonzero.
-    exit $(( ! ! $f ))
+    exit $(( ! ! ${f} ))
 }
 
 typeset -A C
@@ -146,7 +156,7 @@ typeset -A C
 colorize_diff() {
     sed "s/^+/${fg[green]}+/
          s/^-/${fg[red]}-/
-         s/\$/$reset_color/"
+         s/\$/${reset_color}/"
 }
 
 set_colors() {
@@ -158,34 +168,34 @@ set_colors() {
        timeout ${fg_bold[magenta]}
        fail ${fg_bold[red]}
        lex_fail ${fg_bold[cyan]})
-    CEND=$reset_color
+    CEND=${reset_color}
 }
 
 echo "Parameters for this run (override as necessary using environment variables):"
 echo
 
 # Path to the Beluga source distribution.
-echo -e "\t" BELUGADIR: ${BELUGADIR:=$(dirname $0)}
+echo -e "\t" BELUGADIR: "${BELUGADIR:=$(dirname $0)}"
 
-# Set $EXE to the executable to test.
-echo -e "\t" EXE: ${EXE:=$BELUGADIR/bin/beluga}
+# Set ${EXE} to the executable to test.
+echo -e "\t" EXE: "${EXE:=${BELUGADIR}/bin/beluga}"
 
 # Tool for dumping lexer data.
-echo -e "\t" LEX_CHECK: ${LEX_CHECK:=$BELUGADIR/bin/lex_check}
+echo -e "\t" LEX_CHECK: "${LEX_CHECK:=${BELUGADIR}/bin/lex_check}"
 
 # Tool for testing the interactive mode.
-echo -e "\t" REPLAY: ${REPLAY:=$BELUGADIR/bin/replay}
+echo -e "\t" REPLAY: "${REPLAY:=${BELUGADIR}/bin/replay}"
 
 # Test cases.
-echo -e "\t" TESTDIR: ${TESTDIR:=$BELUGADIR/t/code}
+echo -e "\t" TESTDIR: "${TESTDIR:=${BELUGADIR}/t/code}"
 
-echo -e "\t" INTERACTIVE_TESTDIR: ${INTERACTIVE_TESTDIR:=$BELUGADIR/t/interactive}
+echo -e "\t" INTERACTIVE_TESTDIR: "${INTERACTIVE_TESTDIR:=${BELUGADIR}/t/interactive}"
 
 # Test cases.
-echo -e "\t" EXAMPLEDIR: ${EXAMPLEDIR:=$BELUGADIR/examples}
+echo -e "\t" EXAMPLEDIR: "${EXAMPLEDIR:=${BELUGADIR}/examples}"
 
 # Time limit.
-echo -e "\t" TIMEOUT: ${TIMEOUT:=10} seconds
+echo -e "\t" TIMEOUT: "${TIMEOUT:=10}" seconds
 
 echo
 
diff --git a/tools/synconv b/tools/synconv
--- a/tools/synconv
+++ b/tools/synconv
@@ -1,11 +1,13 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+set -u
 
 ##
 ## Configuration
 ##
 
 # Path to the syntax conversion script.
-CONVERT="$(cd $(dirname $0); pwd)/syntax-conv.rb"
+CONVERT="$(cd "$(dirname "$0")"; pwd)/syntax-conv.rb"
 
 # Filters to exclude certain files and directories from translation.
 # The filters are find(1) expressions.
@@ -23,13 +25,13 @@ VERBOSE=0
 usage () {
   echo "Usage:"
   echo
-  echo "  $ $(basename $0) -o <file-out> <file-in>"
+  echo "  $ $(basename "$0") -o <file-out> <file-in>"
   echo
   echo "  Convert the Beluga source file <file-in> to the new 1.0 syntax."
   echo "  If <file-out> is specified with the '-o' switch then the output"
   echo "  is recorded in <file-out>, otherwise it is dumped to STDIN."
   echo
-  echo "  $ $(basename $0) -s <src-dir> -t <dst-dir>"
+  echo "  $ $(basename "$0") -s <src-dir> -t <dst-dir>"
   echo
   echo "  Copy the contents of <src-dir> to a new directory, <dst-dir>,"
   echo "  and the convert every Beluga source file in <dst-dir> to the"
@@ -39,7 +41,7 @@ usage () {
   echo "  you can point to one explicitly using the RUBY environment"
   echo "  variable, as in the following example:"
   echo
-  echo "  $ RUBY=/path/to/ruby $(basename $0) -o <file-out> <file-in>"
+  echo "  $ RUBY=/path/to/ruby $(basename "$0") -o <file-out> <file-in>"
   echo
   echo "Options:"
   echo -e "  -q\t\t No output."
@@ -54,7 +56,7 @@ usage () {
 
 # Check if a program is in PATH.
 exists () {
-  type $1 &>/dev/null
+  type "$1" &>/dev/null
 }
 
 # Abandon ship.
@@ -65,7 +67,7 @@ abort () {
 
 # Get the absolute path of a file or directory.
 abspath () {
-  echo "$(cd $(dirname $1); pwd)/$(basename $1)"
+  echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
 }
 
 
@@ -73,8 +75,8 @@ abspath () {
 ## Preliminary checks
 ##
 
-if [[ ! -z "$RUBY" ]]; then
-  $(exists "$RUBY") ||
+if [[ ! -z "${RUBY}" ]]; then
+  $(exists "${RUBY}") ||
   abort "Error: Unable to find Ruby executable."
 elif exists "ruby1.9"; then
   RUBY="ruby1.9"
@@ -85,11 +87,11 @@ else
 fi
 
 AWKSRC='{if ($1 >= 1 && $2 >= 9) {print 0}}'
-if [[ -z $($RUBY -e 'puts RUBY_VERSION' | tr . ' ' | awk "$AWKSRC") ]]; then
-  abort "Error: $(basename $0) requires Ruby version >= '1.9'."
+if [[ -z $(${RUBY} -e 'puts RUBY_VERSION' | tr . ' ' | awk "${AWKSRC}") ]]; then
+  abort "Error: $(basename "$0") requires Ruby version >= '1.9'."
 fi
 
-[[ -x "$CONVERT" ]] || abort "Error: Conversion script is not executable."
+[[ -x "${CONVERT}" ]] || abort "Error: Conversion script is not executable."
 
 
 ##
@@ -130,50 +132,50 @@ while (( "$#" )); do
   shift
 done
 
-if [[ -z "$SOURCE_DIRECTORY" && -z "$INPUT_FILE" ]]; then
+if [[ -z "${SOURCE_DIRECTORY}" && -z "${INPUT_FILE}" ]]; then
   usage
 fi
 
-if [[ ! -z "$SOURCE_DIRECTORY" ]]; then
-  [[ -d $SOURCE_DIRECTORY && -r $SOURCE_DIRECTORY ]] ||
-  abort "Error: Directory is not accessible, $SOURCE_DIRECTORY."
-  if [[ -z "$TARGET_DIRECTORY" ]]; then
+if [[ ! -z "${SOURCE_DIRECTORY}" ]]; then
+  [[ -d "${SOURCE_DIRECTORY}" && -r "${SOURCE_DIRECTORY}" ]] ||
+  abort "Error: Directory is not accessible, ${SOURCE_DIRECTORY}."
+  if [[ -z "${TARGET_DIRECTORY}" ]]; then
     abort "Error: Target directory must be specified."
   fi
 fi
 
-if [[ ! -z "$TARGET_DIRECTORY" ]]; then
-  if [[ -z "$SOURCE_DIRECTORY" ]]; then
+if [[ ! -z "${TARGET_DIRECTORY}" ]]; then
+  if [[ -z "${SOURCE_DIRECTORY}" ]]; then
     abort "Error: Source directory must be specified."
   fi
-  if [[ ! -d $TARGET_DIRECTORY ]]; then
-    mkdir -p $TARGET_DIRECTORY ||
-    abort "Error: Cannot create $TARGET_DIRECTORY."
-  elif [[ ! -w $TARGET_DIRECTORY ]]; then
-    abort "Error: Cannot access $TARGET_DIRECTORY."
+  if [[ ! -d "${TARGET_DIRECTORY}" ]]; then
+    mkdir -p "${TARGET_DIRECTORY}" ||
+    abort "Error: Cannot create ${TARGET_DIRECTORY}."
+  elif [[ ! -w "${TARGET_DIRECTORY}" ]]; then
+    abort "Error: Cannot access ${TARGET_DIRECTORY}."
   fi
 fi
 
-if [[ ! -z "$INPUT_FILE" ]]; then
-  if [[ ! -z "$SOURCE_DIRECTORY" ]]; then
+if [[ ! -z "${INPUT_FILE}" ]]; then
+  if [[ ! -z "${SOURCE_DIRECTORY}" ]]; then
     abort "Error: Cannot mix directory and file modes."
   fi
-  [[ -f "$INPUT_FILE" && -r "$INPUT_FILE" ]] ||
-  abort "Error: File is not readable, $INPUT_FILE."
+  [[ -f "${INPUT_FILE}" && -r "${INPUT_FILE}" ]] ||
+  abort "Error: File is not readable, ${INPUT_FILE}."
 fi
 
-if [[ ! -z "$OUTPUT_FILE" ]]; then
-  if [[ ! -z "$SOURCE_DIRECTORY" ]]; then
+if [[ ! -z "${OUTPUT_FILE}" ]]; then
+  if [[ ! -z "${SOURCE_DIRECTORY}" ]]; then
     abort "Error: Cannot mix directory and file modes."
   fi
-  if [[ -d "$OUTPUT_FILE" ]]; then
+  if [[ -d "${OUTPUT_FILE}" ]]; then
     abort "Error: Output file exists and is a directory."
-  elif [[ -f "$OUTPUT_FILE" ]]; then
-    [[ -w "$OUTPUT_FILE" ]] ||
+  elif [[ -f "${OUTPUT_FILE}" ]]; then
+    [[ -w "${OUTPUT_FILE}" ]] ||
     abort "Error: Output file exists but it is not writable."
   else
-    OUTPUT_DIR=$(dirname $OUTPUT_FILE)
-    [[ -d $OUTPUT_DIR && -w $OUTPUT_DIR ]] ||
+    OUTPUT_DIR=$(dirname "${OUTPUT_FILE}")
+    [[ -d "${OUTPUT_DIR}" && -w "${OUTPUT_DIR}" ]] ||
     abort "Error: Destination directory of output file is not writable."
   fi
 fi
@@ -183,23 +185,22 @@ fi
 ## Translation
 ##
 
-if [[ ! -z "$INPUT_FILE" ]]; then
-  if [[ ! -z "$OUTPUT_FILE" ]]; then
-    $CONVERT "$INPUT_FILE" > "$OUTPUT_FILE"
+if [[ ! -z "${INPUT_FILE}" ]]; then
+  if [[ ! -z "${OUTPUT_FILE}" ]]; then
+    ${CONVERT} "${INPUT_FILE}" > "${OUTPUT_FILE}"
   else
-    $CONVERT "$INPUT_FILE"
+    ${CONVERT} "${INPUT_FILE}"
   fi
 else
-  SRCDIR=$(abspath $SOURCE_DIRECTORY)
-  rm -rf $TARGET_DIRECTORY
-  cp -r $SOURCE_DIRECTORY/ $TARGET_DIRECTORY/
-  pushd $TARGET_DIRECTORY &>/dev/null
+  rm -rf "${TARGET_DIRECTORY}"
+  cp -r "${SOURCE_DIRECTORY}/" "${TARGET_DIRECTORY}/"
+  pushd "${TARGET_DIRECTORY}" &>/dev/null
   echo find . -name "*.bel" -not "${IGNORE[@]}"
   for f in $(find . -name "*.bel" "${IGNORE[@]}"); do
-      [[ $VERBOSE = 0 ]] && echo -n "Converting: $f"
-      t=$(mktemp -q "$f-XXXX.tmp") &&
-      $CONVERT "$f" > "$t" && rm -f "$f" && mv "$t" "$f" &&
-      [[ $VERBOSE = 0 ]] && echo " => DONE." || echo " => FAILED."
+      [[ ${VERBOSE} = 0 ]] && echo -n "Converting: ${f}"
+      t=$(mktemp -q "${f}-XXXX.tmp") &&
+      ${CONVERT} "${f}" > "${t}" && rm -f "${f}" && mv "${t}" "${f}" &&
+      [[ ${VERBOSE} = 0 ]] && echo " => DONE." || echo " => FAILED."
   done
   popd &>/dev/null
 fi
