Integrate lexer testing with test harness
This obviates the need for the scripts lex_check.sh and lex_check_all.sh
that were previously introduced.
Now, when running the test harness, the program lex_dump will be used to
compute where Beluga thinks the input ends and wc will be used to
compute where the file *really* ends. If these counts are mismatched,
then the message LEXER FAILURE will appear (in cyan) before the semantic
test status (DONE, FAIL, TIMEOUT, etc.).
The total count of lexer failures is tallied and displayed in the test
summary at the end.

The Makefile is adjusted so that the `all` build target will also
build the lex_dump program needed for testing the lexer.

diff --git a/TEST b/TEST
--- a/TEST
+++ b/TEST
@@ -28,6 +28,9 @@ echo -e "\t" BELUGADIR: ${BELUGADIR:=$(dirname $0)}
 # Set $EXE to the executable to test.
 echo -e "\t" EXE: ${EXE:=$BELUGADIR/bin/beluga}
 
+# Tool for dumping lexer data.
+echo -e "\t" LEX_DUMP: ${LEX_DUMP:=$BELUGADIR/bin/lex_dump}
+
 # Test cases.
 echo -e "\t" TESTDIR: ${TESTDIR:=$BELUGADIR/t}
 
@@ -44,69 +47,97 @@ setopt null_glob
 
 # Find test cases.
 test_cases() {
-    for dir in $TESTDIR/**/ $EXAMPLEDIR/**/
-    do
-	cfgs=(${dir}*.cfg)
-	if (( ${#cfgs[@]} > 0 ))
-	then
-	    print -C1 ${dir}*.cfg
-	else
-	    print -C1 ${dir}*.bel
-	fi
+    for dir in $TESTDIR/**/ $EXAMPLEDIR/**/ ; do
+        cfgs=(${dir}*.cfg)
+        if (( ${#cfgs[@]} > 0 )) ; then
+            print -C1 ${dir}*.cfg
+        else
+            print -C1 ${dir}*.bel
+        fi
     done
 }
 
 sort_cases() {
     cases=($(</dev/stdin))
-    for i in ${(M)cases#*.bel}; do wc -c $i; done | sort -n | awk '{print $2}'
+    for i in ${(M)cases#*.bel}; do
+        wc -c $i;
+    done | sort -n | awk '{print $2}'
     print -C1 ${(M)cases#*.cfg}
 }
 
+# use lex_dump to calculate where Beluga thinks the file ends.
+beluga-eoi() {
+    # The lex_dump output looks like:
+    # EOI: 21-21
+    $LEX_DUMP "$1" | grep EOI | head -n 1 | cut -d " " -f2 | cut -d "-" -f1
+}
+
+true-eoi() {
+    # wc output looks like:
+    # 21 foo.bel
+    # We use `wc -m` to count *characters* (UTF-8-encoded unicode code
+    # points) so that the thing we're counting here coincides with
+    # Beluga's notion of "character" (i.e. unicode code points, as per
+    # the use of ulex.)
+    LANG=en_US.UTF-8 wc -m "$1" | cut -d " " -f1
+}
+
+lex-check() {
+    local FILE="$1"
+    local BELUGA_COUNT=$(beluga-eoi "$FILE")
+    local TRUE_COUNT=$(true-eoi "$FILE")
+    test $BELUGA_COUNT -eq $TRUE_COUNT
+}
+
 do_testing() {
-    local n=0 success=0 fail=0 timeout=0 admissible=0
+    local n=0 success=0 fail=0 timeout=0 admissible=0 lexer_fail=0
 
     # Limit runtime of each test case, in seconds.
     ulimit -t $TIMEOUT
 
-    for i in $(test_cases | sort -n)
-    do
-	n=$((n+1))
-	echo -ne "$C[start]**$CEND TEST $n: $i ... "
+    for i in $(test_cases | sort -n) ; do
+        n=$((n+1))
+        echo -ne "$C[start]**$CEND TEST $n: $i ... "
 
-	result=$($EXE +test $* $i 2>&1)
-	exit_code=$?
-	diff_result=$(printf "%s" $result | diff -b -u $i.out - 2>/dev/null)
-	# diff responds 0 if same, 1 if different, 2 if couldn't compare.
-	diff_code=$?
+        if ! lex-check "$i" ; then
+            lexer_fail=$((lexer_fail+1))
+            echo -en "$C[lex_fail]LEXER FAILURE$CEND "
+        fi
 
-	if [[ $exit_code -eq 152 ]]
-	then
-	    echo -e "$C[timeout]TIMEOUT$CEND"
-	    timeout=$((timeout+1))
-	elif [[ $diff_code -eq 0 || (exit_code -eq 0 && $diff_code -eq 2) ]]
-	then
-	    echo -e "$C[done]DONE$CEND"
-	    success=$((success+1))
-	else
-	    grep --quiet "$i" .admissible-fail
-	    is_adm=$?
-	    if [[ $is_adm -eq 0  ]] 
-	    then
-		echo -e "$C[admissible]ADMISSIBLE$CEND"
-		admissible=$((admissible+1))
-	    else
-		echo -e "$C[fail]FAIL$CEND"
-		fail=$((fail+1))
-	    fi
-	    [[ -z "$diff_result" ]] && echo "$result" || (echo "$diff_result" | colorize_diff)
-	fi
+        result=$($EXE +test $* $i 2>&1)
+        exit_code=$?
+        diff_result=$(printf "%s" $result | diff -b -u $i.out - 2>/dev/null)
+        # diff responds 0 if same, 1 if different, 2 if couldn't compare.
+        diff_code=$?
 
-	[[ -n $RESET && -f $i.out ]] && echo "$result" > $i.out
+        if [[ $exit_code -eq 152 ]]
+        then
+            echo -e "$C[timeout]TIMEOUT$CEND"
+            timeout=$((timeout+1))
+        elif [[ $diff_code -eq 0 || (exit_code -eq 0 && $diff_code -eq 2) ]]
+        then
+            echo -e "$C[done]DONE$CEND"
+            success=$((success+1))
+        else
+            grep --quiet "$i" .admissible-fail
+            is_adm=$?
+            if [[ $is_adm -eq 0  ]]; then
+                echo -e "$C[admissible]ADMISSIBLE$CEND"
+                admissible=$((admissible+1))
+            else
+                echo -e "$C[fail]FAIL$CEND"
+                fail=$((fail+1))
+            fi
+            [[ -z "$diff_result" ]] && echo "$result" || (echo "$diff_result" | colorize_diff)
+        fi
+
+        [[ -n $RESET && -f $i.out ]] && echo "$result" > $i.out
     done
 
     echo
     echo Successes: $success
     echo Failures: $fail
+    echo Lexer failures: $lexer_fail
     echo Admissible failures: $admissible
     echo Timeouts: $timeout
     echo Total: $n
@@ -114,7 +145,7 @@ do_testing() {
     echo
     times
 
-    f=$((fail + timeout))
+    f=$((fail + timeout + lexer_fail))
     # If not all tests succeeded then exit with non-zero status.
     [[ $f -eq 0 ]] || exit 1
     exit 0
@@ -131,7 +162,7 @@ colorize_diff() {
 set_colors() {
     autoload colors
     colors
-    C=(start ${fg[blue]} admissible ${fg_bold[yellow]} done ${fg_bold[green]} timeout ${fg_bold[magenta]} fail ${fg_bold[red]})
+    C=(start ${fg[blue]} admissible ${fg_bold[yellow]} done ${fg_bold[green]} timeout ${fg_bold[magenta]} fail ${fg_bold[red]} lex_fail ${fg_bold[cyan]})
     CEND=$reset_color
 }
 
@@ -141,37 +172,37 @@ set_colors() {
 while true
 do
     case "$1" in
-	-h|--help)
-	    usage
-	    exit 0
-	    ;;
-	-c|--colour|--color)
-	    set_colors
-	    shift
-	    ;;
-	--noexamples)
-	    EXAMPLEDIR=/dev/null
-	    shift
-	    ;;
-	--examples)
-	    TESTDIR=/dev/null
-	    shift
-	    ;;
-	--reset)
-	    RESET=true
-	    shift
-	    ;;
-	--)
-	    shift
-	    break
-	    ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        -c|--colour|--color)
+            set_colors
+            shift
+            ;;
+        --noexamples)
+            EXAMPLEDIR=/dev/null
+            shift
+            ;;
+        --examples)
+            TESTDIR=/dev/null
+            shift
+            ;;
+        --reset)
+            RESET=true
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
         "")
             break
             ;;
-	*)
+        *)
             echo "Unrecognized option $1."
-	    echo "Make sure to write -- before any argument that should be passed to Beluga."
-	    exit 2
+            echo "Make sure to write -- before any argument that should be passed to Beluga."
+            exit 2
     esac
 done
 
