Use bash for the TEST script instead of zsh

diff --git a/TEST b/TEST
--- a/TEST
+++ b/TEST
@@ -1,8 +1,289 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env bash
 
+# Emit an error if undefined variable is used.
 set -u
 
-usage() {
+# Allow glob to match files and directories in subdirectories
+shopt -s globstar
+shopt -s nullglob
+
+# Option flags.
+declare FORCE_COLOR_OUTPUT=""
+declare NO_EXAMPLES=""
+declare ONLY_EXAMPLES=""
+declare ONLY_INTERACTIVES=""
+declare RESET_OUT_FILES=""
+declare STOP_ON_FAILURE=""
+
+declare -a BELUGA_FLAGS=()
+
+# Path to the Beluga source distribution.
+declare -r BELUGADIR=${BELUGADIR:-$(dirname "${BASH_SOURCE[0]}")}
+
+# Path to the Beluga executable to test.
+declare -r EXE=${EXE:-"${BELUGADIR}/bin/beluga"}
+
+# Path to the Beluga lex_check to test.
+declare -r LEX_CHECK=${LEX_CHECK:-"${BELUGADIR}/bin/lex_check"}
+
+# Path to the Beluga replay to test.
+declare -r REPLAY=${REPLAY:-"${BELUGADIR}/bin/replay"}
+
+declare -r TESTDIR=${TESTDIR:-"${BELUGADIR}/t/code"}
+declare -r EXAMPLEDIR=${EXAMPLEDIR:-"${BELUGADIR}/examples"}
+declare -r INTERACTIVE_TESTDIR=${INTERACTIVE_TESTDIR:-"${BELUGADIR}/t/interactive"}
+
+declare -i TIMEOUT=${TIMEOUT:-10}
+
+declare -A TEST_RESULT=(
+    [total]=0
+    [success]=0
+    [timeout]=0
+    [admissible]=0
+    [fail]=0
+    [lexer_fail]=0
+    [replay_fail]=0
+)
+
+declare -A C=(
+    [start]=""
+    [admissible]=""
+    [ok]=""
+    [timeout]=""
+    [fail]=""
+    [lex_fail]=""
+    [added]=""
+    [removed]=""
+)
+declare CEND=""
+
+function main {
+    parse_opts "$@"
+    if [[ -t 1 || -n "${FORCE_COLOR_OUTPUT}" ]]; then
+        set_colors
+    fi
+    print_paths
+    do_testing
+}
+
+function parse_opts {
+    while [ "$#" -gt 0 ]; do
+        case "$1" in
+            -h|--help)
+                usage
+                exit 0
+                ;;
+            -c|--colour|--color)
+                FORCE_COLOR_OUTPUT="true"
+                ;;
+            --noexamples)
+                NO_EXAMPLES="true"
+                ;;
+            --examples)
+                ONLY_EXAMPLES="true"
+                ;;
+            --reset)
+                RESET_OUT_FILES="true"
+                ;;
+            --interactive)
+                ONLY_INTERACTIVES="true"
+                ;;
+            --stop)
+                STOP_ON_FAILURE="true"
+                ;;
+            --)
+                shift
+                break
+                ;;
+            "")
+                break
+                ;;
+            *)
+                echo "Unrecognized option $1."
+                echo "Make sure to write -- before any argument that should be passed to Beluga."
+                exit 2
+                ;;
+        esac
+        shift
+    done
+
+    BELUGA_FLAGS=("$@")
+}
+
+function do_testing {
+    local exit_code=0 is_failed=0
+    # Limit runtime of each test case, in seconds.
+    ulimit -t "${TIMEOUT}"
+
+    if [[ -z "${NO_EXAMPLES}" && -z "${ONLY_INTERACTIVES}" ]]; then
+        echo "===== EXAMPLES ====="
+
+        for f in $(find_compiler_tests_in "${EXAMPLEDIR}"); do
+            start_test_case "${f}"
+
+            if ! lex_check_test_case "${f}"; then
+                continue
+            fi
+
+            check_compiler_test_case_output "${f}"
+        done
+    fi
+
+    if [[ -z "${ONLY_EXAMPLES}" && -z "${ONLY_INTERACTIVES}" ]]; then
+        echo "===== COMPILER TESTS ====="
+
+        for f in $(find_compiler_tests_in "${TESTDIR}") ; do
+            start_test_case "${f}"
+
+            if ! lex_check_test_case "${f}"; then
+                continue
+            fi
+
+            check_compiler_test_case_output "${f}"
+        done
+    fi
+
+    echo "===== INTERACTIVE MODE TESTS ====="
+
+    for f in $(find "${INTERACTIVE_TESTDIR}" -type f | sort -n) ; do
+        start_test_case "${f}"
+
+        ${REPLAY} "${f}" > /dev/null 2>&1
+        exit_code=$?
+
+        if [ "${exit_code}" -eq 152 ] ; then
+            process_result "timeout" "TIMEOUT"
+        elif [ "${exit_code}" -ne 0 ] ; then
+            process_result "replay_fail" "FAIL"
+        else
+            process_result "success" "OK"
+        fi
+    done
+
+    echo
+    echo "Successes: ${TEST_RESULT[success]}"
+    echo "Failures: ${TEST_RESULT[fail]}"
+    echo "Lexer failures: ${TEST_RESULT[lexer_fail]}"
+    echo "Admissible failures: ${TEST_RESULT[admissible]}"
+    echo "Timeouts: ${TEST_RESULT[timeout]}"
+    echo "Interactive mode failures: ${TEST_RESULT[replay_fail]}"
+    echo "Total: ${TEST_RESULT[total]}"
+    echo
+    times
+
+    (( is_failed=TEST_RESULT[fail] + TEST_RESULT[timeout] + TEST_RESULT[lexer_fail] + TEST_RESULT[replay_fail] ))
+    # If not all tests succeeded then exit with non-zero status.
+    # double-negate the failure count to get 0 if it was zero, and
+    # 1 if it was nonzero.
+    exit $(( ! ! is_failed ))
+}
+
+function lex_check_test_case {
+    local -r file_path=$1
+
+    local exit_code
+
+    ${LEX_CHECK} "${file_path}" > /dev/null 2>&1
+    exit_code=$?
+
+    if [ "${exit_code}" -eq 2 ] ; then
+        process_result "lexer_fail" "FATAL LEXER FAILURE"
+        stop_on_failure
+        return 1
+    fi
+
+    if [ "${exit_code}" -ne 0 ] ; then
+        process_result "lexer_fail" "LEXER FAILURE"
+        stop_on_failure
+        return 1
+    fi
+
+    return 0
+}
+
+function check_compiler_test_case_output {
+    local -r file_path=$1
+
+    local output exit_code diff_output diff_code
+
+    output=$(${EXE} +test "${BELUGA_FLAGS[@]}" "${file_path}" 2>&1)
+    exit_code=$?
+    diff_output=$(printf "%s" "${output}" | diff -b -u "${file_path}.out" - 2>/dev/null)
+    # diff responds 0 if same, 1 if different, 2 if couldn't compare.
+    diff_code=$?
+
+    if [ "${exit_code}" -eq 152 ];then
+        process_result "timeout" "TIMEOUT"
+        stop_on_failure
+    elif [[ "${diff_code}" -eq 0 || ("${exit_code}" -eq 0 && "${diff_code}" -eq 2) ]]; then
+        process_result "success" "OK"
+    else
+        if grep --quiet "${file_path}" .admissible-fail ; then
+            process_result "admissible" "ADMISSIBLE"
+        else
+            process_result "fail" "FAIL"
+
+            if [ -z "${diff_output}" ]; then
+                echo "${output}"
+            else
+                echo "${diff_output}" | colorize_diff
+            fi
+
+            stop_on_failure
+        fi
+    fi
+
+    if [[ -n "${RESET_OUT_FILES}" && -f "${file_path}.out" ]]; then
+        echo "${output}" > "${file_path}.out"
+    fi
+}
+
+function start_test_case {
+    local -r file_path=$1
+
+    (( TEST_RESULT[total]+=1 ))
+    echo -ne "${C[start]}**${CEND} TEST ${TEST_RESULT[total]}: ${file_path} ... "
+}
+
+function process_result {
+    local -r type=$1 message=$2
+
+    local -Ar type_to_color=(
+        [success]="ok"
+        [timeout]="timeout"
+        [admissible]="admissible"
+        [fail]="fail"
+        [lexer_fail]="lexer_fail"
+        [replay_fail]="fail"
+    )
+    local -r color=${type_to_color[${type}]}
+
+    echo -e "${C[${color}]}${message}${CEND}"
+    (( TEST_RESULT[${type}]+=1 ))
+}
+
+function stop_on_failure {
+    if [ -n "${STOP_ON_FAILURE}" ]; then
+        exit 1
+    fi
+}
+
+function find_compiler_tests_in {
+    local -a tests
+
+    for dir in "$1"/**/; do
+        tests=("${dir}"*.cfg)
+        if [ "${#tests[@]}" -eq 0 ]; then
+            tests=("${dir}"*.bel)
+        fi
+
+        if [ "${#tests[@]}" -gt 0 ]; then
+            printf "%s\n" "${tests[@]}"
+        fi
+    done | sort -n
+}
+
+function usage {
     echo "Usage: $0 [test-options] -- [beluga-options]"
     echo
     echo "Synopsis: test harness for Beluga."
@@ -23,213 +304,36 @@ usage() {
     echo "  - To inhibit testing .bel files, put an empty test.cfg in that directory."
 }
 
-STOP=0
-RESET=
-
-# Allow file globs to match nothing.
-setopt null_glob
-
-# Find test cases.
-test_cases() {
-    for dir in ${TESTDIR}/**/ ${EXAMPLEDIR}/**/ ; do
-        cfgs=(${dir}*.cfg)
-        if (( ${#cfgs[@]} > 0 )) ; then
-            print -C1 ${dir}*.cfg
-        else
-            print -C1 ${dir}*.bel
-        fi
-    done
-}
-
-do_testing() {
-    local n=0 success=0 fail=0 timeout=0 admissible=0 lexer_fail=0 replay_fail=0
-
-    # Limit runtime of each test case, in seconds.
-    ulimit -t "${TIMEOUT}"
-
-    for i in $(test_cases | sort -n) ; do
-        n=$((n+1))
-        echo -ne "${C[start]}**${CEND} TEST ${n}: ${i} ... "
-
-        result=$(${LEX_CHECK} "${i}" 2>&1)
-        exit_code=$?
-
-        if [ ${exit_code} -eq 2 ] ; then
-            let lexer_fail=lexer_fail+1
-            echo -e "${C[lex_fail]}FATAL LEXER FAILURE${CEND}"
-            test ${STOP} -eq 1 && exit 1 || continue
-        fi
-
-        if [ ${exit_code} -ne 0 ] ; then
-            lexer_fail=$((lexer_fail+1))
-            echo -en "${C[lex_fail]}LEXER FAILURE${CEND}"
-            test ${STOP} -eq 1 && exit 1
-        fi
-
-        result=$(${EXE} +test $* "${i}" 2>&1)
-        exit_code=$?
-        diff_result=$(printf "%s" "${result}" | diff -b -u "${i}.out" - 2>/dev/null)
-        # diff responds 0 if same, 1 if different, 2 if couldn't compare.
-        diff_code=$?
-
-        if [[ ${exit_code} -eq 152 ]]
-        then
-            echo -e "${C[timeout]}TIMEOUT${CEND}"
-            timeout=$((timeout+1))
-            test ${STOP} -eq 1 && exit 1
-        elif [[ "${diff_code}" -eq 0 || (exit_code -eq 0 && "${diff_code}" -eq 2) ]]
-        then
-            echo -e "${C[ok]}OK${CEND}"
-            success=$((success+1))
-        else
-            if grep --quiet "${i}" .admissible-fail ; then
-                echo -e "${C[admissible]}ADMISSIBLE${CEND}"
-                admissible=$((admissible+1))
-            else
-                echo -e "${C[fail]}FAIL${CEND}"
-                fail=$((fail+1))
-
-                if [[ -z "${diff_result}" ]]; then
-                    echo "${result}"
-                else
-                    echo "${diff_result}" | colorize_diff
-                fi
-
-                test ${STOP} -eq 1 && exit 1
-            fi
-        fi
-
-        [[ -n "${RESET}" && -f "${i}.out" ]] && echo "${result}" > "${i}.out"
-    done
-
-    echo "===== INTERACTIVE MODE TESTS ====="
-
-    for i in $(find "${INTERACTIVE_TESTDIR}" -type f | sort -n) ; do
-        n=$((n+1))
-        echo -ne "${C[start]}**${CEND} TEST ${n}: ${i} ... "
-
-        result=$(${REPLAY} "${i}" 2>&1)
-        exit_code=$?
-
-        if [ ${exit_code} -eq 152 ] ; then
-            echo -e "${C[timeout]}TIMEOUT${CEND}"
-            timeout=$((timeout + 1))
-        elif [ ${exit_code} -ne 0 ] ; then
-            echo -e "${C[fail]}FAIL${CEND}"
-            replay_fail=$((replay_fail + 1))
-        else
-            echo -e "${C[ok]}OK${CEND}"
-        fi
-    done
-
+function print_paths {
+    echo "Parameters for this run (override as necessary using environment variables):"
     echo
-    echo Successes: ${success}
-    echo Failures: ${fail}
-    echo Lexer failures: ${lexer_fail}
-    echo Admissible failures: ${admissible}
-    echo Timeouts: ${timeout}
-    echo Interactive mode failures: ${replay_fail}
-    echo Total: ${n}
-
+    echo -e "\t BELUGADIR: ${BELUGADIR}"
+    echo -e "\t EXE: ${EXE}"
+    echo -e "\t LEX_CHECK: ${LEX_CHECK}"
+    echo -e "\t REPLAY: ${REPLAY}"
+    echo -e "\t TESTDIR: ${TESTDIR}"
+    echo -e "\t INTERACTIVE_TESTDIR: ${INTERACTIVE_TESTDIR}"
+    echo -e "\t EXAMPLEDIR: ${EXAMPLEDIR}"
+    echo -e "\t TIMEOUT: ${TIMEOUT}" seconds
     echo
-    times
-
-    f=$((fail + timeout + lexer_fail + replay_fail))
-    # If not all tests succeeded then exit with non-zero status.
-    # double-negate the failure count to get 0 if it was zero, and
-    # 1 if it was nonzero.
-    exit $(( ! ! ${f} ))
 }
 
-typeset -A C
-
-colorize_diff() {
-    sed "s/^+/${fg[green]}+/
-         s/^-/${fg[red]}-/
-         s/\$/${reset_color}/"
+function set_colors {
+    C[start]="\x1b[34m"              # foreground blue
+    C[admissible]="\x1b[01;33m"      # foreground bold yellow
+    C[ok]="\x1b[01;32m"              # foreground bold green
+    C[timeout]="\x1b[01;35m"         # foreground bold magenta
+    C[fail]="\x1b[01;31m"            # foreground bold red
+    C[lexer_fail]="\x1b[01;36m"      # foreground bold cyan
+    C[added]="\x1b[32m"              # foreground green
+    C[removed]="\x1b[31m"            # foreground red
+    CEND="\x1b[00m"                     # reset colors
 }
 
-set_colors() {
-    autoload colors
-    colors
-    C=(start ${fg[blue]}
-       admissible ${fg_bold[yellow]}
-       ok ${fg_bold[green]}
-       timeout ${fg_bold[magenta]}
-       fail ${fg_bold[red]}
-       lex_fail ${fg_bold[cyan]})
-    CEND=${reset_color}
+function colorize_diff {
+    sed "s/^+/${C[added]}+/
+         s/^-/${C[removed]}-/
+         s/\$/${CEND}/"
 }
 
-echo "Parameters for this run (override as necessary using environment variables):"
-echo
-
-# Path to the Beluga source distribution.
-echo -e "\t" BELUGADIR: "${BELUGADIR:=$(dirname $0)}"
-
-# Set ${EXE} to the executable to test.
-echo -e "\t" EXE: "${EXE:=${BELUGADIR}/bin/beluga}"
-
-# Tool for dumping lexer data.
-echo -e "\t" LEX_CHECK: "${LEX_CHECK:=${BELUGADIR}/bin/lex_check}"
-
-# Tool for testing the interactive mode.
-echo -e "\t" REPLAY: "${REPLAY:=${BELUGADIR}/bin/replay}"
-
-# Test cases.
-echo -e "\t" TESTDIR: "${TESTDIR:=${BELUGADIR}/t/code}"
-
-echo -e "\t" INTERACTIVE_TESTDIR: "${INTERACTIVE_TESTDIR:=${BELUGADIR}/t/interactive}"
-
-# Test cases.
-echo -e "\t" EXAMPLEDIR: "${EXAMPLEDIR:=${BELUGADIR}/examples}"
-
-# Time limit.
-echo -e "\t" TIMEOUT: "${TIMEOUT:=10}" seconds
-
-echo
-
-# By default, use colors only when connected to a terminal.
-[[ -t 1 ]] && set_colors
-
-while (( $# )) ; do
-    case "$1" in
-        -h|--help)
-            usage
-            exit 0
-            ;;
-        -c|--colour|--color)
-            set_colors
-            ;;
-        --noexamples)
-            EXAMPLEDIR=/dev/null
-            ;;
-        --examples)
-            TESTDIR=/dev/null
-            ;;
-        --reset)
-            RESET=true
-            ;;
-        --interactive)
-            EXAMPLEDIR=/dev/null
-            TESTDIR=/dev/null
-            ;;
-        --stop)
-            STOP=1
-            ;;
-        --)
-            shift
-            break
-            ;;
-        "")
-            break
-            ;;
-        *)
-            echo "Unrecognized option $1."
-            echo "Make sure to write -- before any argument that should be passed to Beluga."
-            exit 2
-    esac
-    shift
-done
-
-do_testing $*
+main "$@"
