improve test infrastructure; fix travis
Travis was not running tests correctly since I switched to one of the
official opam Travis CI scripts.

This is corrected by adding extra steps to the build instructions in
the beluga.opam, specifically to run TEST. However, we can't just run
TEST because it needs the paths to Beluga and all the ancillary
programs, viz. lex_check, replay, and harpoon. So instead we invoke
TEST through dune, since `dune exec` locally adjusts PATH to include
this programs.

TEST has also been improved:
- it prints the error message generated by replay if any;
- it checks the existence of all the programs before beginning to run
  the tests.

Some other minor changes:
- the opam synopsis for Beluga is corrected
- the makefile includes a `test` target for running TEST using
  dune. This is now the preferred way to run the test suite.

diff --git a/TEST b/TEST
--- a/TEST
+++ b/TEST
@@ -19,27 +19,37 @@ declare STOP_ON_FAILURE=""
 
 declare -a BELUGA_FLAGS=()
 
-# Path to the Beluga source distribution.
-declare -r BELUGADIR=${BELUGADIR:-$(dirname "${BASH_SOURCE[0]}")}
-
 # Path to the Beluga executable to test.
-declare -r EXE=${EXE:-"${BELUGADIR}/bin/beluga"}
+declare -r EXE=${EXE:-"beluga"}
 
 # Path to the Beluga lex_check to test.
-declare -r LEX_CHECK=${LEX_CHECK:-"${BELUGADIR}/bin/lex_check"}
+declare -r LEX_CHECK=${LEX_CHECK:-"lex_check"}
 
 # Path to the Beluga replay to test.
-declare -r REPLAY=${REPLAY:-"${BELUGADIR}/bin/replay"}
+declare -r REPLAY=${REPLAY:-"replay"}
 
 # Path to the Harpoon to test.
-declare -r HARPOON=${HARPOON:-"${BELUGADIR}/bin/harpoon"}
+declare -r HARPOON=${HARPOON:-"harpoon"}
 
-declare -r TESTDIR=${TESTDIR:-"${BELUGADIR}/t/code"}
-declare -r EXAMPLEDIR=${EXAMPLEDIR:-"${BELUGADIR}/examples"}
-declare -r INTERACTIVE_TESTDIR=${INTERACTIVE_TESTDIR:-"${BELUGADIR}/t/interactive"}
-declare -r HARPOON_TESTDIR=${HARPOON_TESTDIR:-"${BELUGADIR}/t/harpoon"}
+declare -r TESTDIR=${TESTDIR:-"./t/code"}
+declare -r EXAMPLEDIR=${EXAMPLEDIR:-"./examples"}
+declare -r INTERACTIVE_TESTDIR=${INTERACTIVE_TESTDIR:-"./t/interactive"}
+declare -r HARPOON_TESTDIR=${HARPOON_TESTDIR:-"./t/harpoon"}
 
 declare -i TIMEOUT=${TIMEOUT:-10}
+
+die () {
+    echo "Fatal error: " "$@" >&2
+    exit 1
+}
+
+require_program_exists () {
+    command -v "$1" >/dev/null 2>&1 || die "program" "$1" "could not found."
+}
+
+for p in "${EXE}" "${LEX_CHECK}" "${REPLAY}" "${HARPOON}" ; do
+    require_program_exists "${p}"
+done
 
 declare -A TEST_RESULT=(
     [total]=0
@@ -173,13 +183,14 @@ function do_testing {
         for f in $(find "${INTERACTIVE_TESTDIR}" -type f | sort -n) ; do
             start_test_case "${f}"
 
-            ${REPLAY} "${f}" > /dev/null 2>&1
+            local output="$(${REPLAY} "${EXE}" "${f}")"
             exit_code=$?
 
             if [ "${exit_code}" -eq 152 ] ; then
                 process_result "timeout" "TIMEOUT"
             elif [ "${exit_code}" -ne 0 ] ; then
                 process_result "replay_fail" "FAIL"
+                echo "${output}"
             else
                 process_result "success" "OK"
             fi
@@ -395,7 +406,6 @@ function usage {
 function print_paths {
     echo "Parameters for this run (override as necessary using environment variables):"
     echo
-    echo -e "\t BELUGADIR: ${BELUGADIR}"
     echo -e "\t EXE: ${EXE}"
     echo -e "\t LEX_CHECK: ${LEX_CHECK}"
     echo -e "\t REPLAY: ${REPLAY}"
