tools/synconv: Updated script to first look for "ruby1.9" in $PATH, set                increased verbosity by default and use `mktemp' to                generate temporary files.
examples1.0: Image of `examples' directory with `.bel' source files
             converted to the 1.0 syntax, with a few exceptions:
             `evaluation.bel', `evaluation-seq.bel' and
             `evaluation-2.bel'.

diff --git a/tools/synconv b/tools/synconv
--- a/tools/synconv
+++ b/tools/synconv
@@ -12,7 +12,7 @@ IGNORE=("eq-proof-full-crec.bel" "evaluation.bel" "evaluation-seq.bel" \
   "evaluation-2.bel")
 
 # Increased verbosity, set when VERBOSE=0.
-VERBOSE=1
+VERBOSE=0
 
 
 ##
@@ -34,14 +34,14 @@ usage () {
   echo "  and the convert every Beluga source file in <dst-dir> to the"
   echo "  1.0 syntax."
   echo
-  echo "  If a suitable ruby interpreter cannot be found automatically,"
+  echo "  If a suitable Ruby interpreter cannot be found automatically,"
   echo "  you can point to one explicitly using the RUBY environment"
   echo "  variable, as in the following example:"
   echo
   echo "  $ RUBY=/path/to/ruby $(basename $0) -o <file-out> <file-in>"
   echo
   echo "Options:"
-  echo -e "  -v\t\t Increased verbosity."
+  echo -e "  -q\t\t No output."
   echo -e "  -h\t\t Show this message."
   exit 1
 }
@@ -73,8 +73,10 @@ abspath () {
 ##
 
 if [[ ! -z "$RUBY" ]]; then
-  [[ -x "$RUBY" ]] ||
+  $(exists "$RUBY") ||
   abort "Error: Unable to find Ruby executable."
+elif exists "ruby1.9"; then
+  RUBY="ruby1.9"
 elif exists "ruby"; then
   RUBY="ruby"
 else
@@ -114,8 +116,8 @@ while (( "$#" )); do
       shift
       OUTPUT_FILE="$1"
       ;;
-    -v)
-      VERBOSE=0
+    -q)
+      VERBOSE=1
       ;;
     -h|--help)
       usage
@@ -203,8 +205,9 @@ else
     done
     if [[ $skip = 1 ]]; then
       [[ $VERBOSE = 0 ]] && echo -n "Converting: $f"
-      $CONVERT "$f" > "$f.tmp" && rm -f "$f" && mv "$f.tmp" "$f"
-      [[ $VERBOSE = 0 ]] && echo " => DONE."
+      t=$(mktemp -q "$f-XXXX.tmp") &&
+      $CONVERT "$f" > "$t" && rm -f "$f" && mv "$t" "$f" &&
+      [[ $VERBOSE = 0 ]] && echo " => DONE." || echo " => FAILED."
     else
       [[ $VERBOSE = 0 ]] && echo "Skipping: $f"
     fi
